[project]
name = "youtube-transcribe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-api-python-client>=2.158.0",
    "yt-dlp>=2024.12.23",
]
